# Generated by Django 2.2.21 on 2021-10-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybooks',
            name='last_library_activity',
            field=models.ManyToManyField(blank=True, null=True, related_name='last_activity', to='libraryApp.LibraryActivity'),
        ),
    ]
