# Generated by Django 2.2.21 on 2021-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_auto_20211009_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybooks',
            name='library',
        ),
        migrations.AddField(
            model_name='librarybooks',
            name='library',
            field=models.ManyToManyField(related_name='library', to='libraryApp.Libraries', verbose_name='Lirary-book pool'),
        ),
    ]
